### PR TITLE
Update README for readability

### PR DESCRIPTION
**Pull request by LorenzoSapora**
- Improve brief description
- Fix section headlines
- Cut reductive 'You can' verbiage.
- Fix basic usage wording
- Include a more complete basic example

### CODE REVIEW

**Comment by LorenzoSapora** [comment]
Not finished with the README, yet, but wanted to push a PR for your thoughts on the improvements.

I'll add some commits later tonight/tomorrow, and let you know when this is ready to merge.

**Comment by milewski** [comment]
Awesome, my English sucks, the way you rephrase it sounds much better, I tried to make the example match the a screen shoot, so somehow people would make the connection that if you uncheck the column the field also disappears from the resource table, and when you execulte any action the selected fields are passed along on your request so you can do things like.. Export the table to excell only containing the selected columns etc... perhaps with your change will require also a new screenshoot

**Comment by LorenzoSapora** [comment]
Yeah, I'll update the screenshots after I've refined the README a little more. I'll jump back in tomorrow 👍

**Comment by milewski** [comment]
There are also a bunch of filters we created to work with this package :

https://github.com/dcasia/nova-pill-filter
https://github.com/dcasia/nova-slider-filter
https://github.com/dcasia/nova-range-input-filter

**Comment by milewski** [comment]
Can merge? 😄

**Pull request closed without merging**
