### PR TITLE
Save filter state

### PR DESCRIPTION
**Pull request by keizah7**
#52 #51

### CODE REVIEW

**Comment by milewski** [comment]
Awesome thanks!

**Comment by Andriichello** [comment]
There is a problem when columns filter is used on more than one resource, because only the last selected columns are saved to the session, but different resources usually have different columns. So I suggest that it's better to save filter into the session with resources class name slug.

**Comment by Andriichello** [comment]
This is how I did it. I created methods to make session key depending on resource name slug and then replaced call to 
`session('mega-filter-columns')`
with 
`session($this->getSessionKey())`;

`trait MegaFilterable
{
    use HasMegaFilterTrait;

    /**
     * Get current resource slug.
     *
     * @return string
     */
    public function getResourceSlug(): string
    {
        $name = Str::of(static::class)
            ->explode('\\')
            ->last();

        return Str::snake($name, '-');
    }

    /**
     * Get current resource's filter storage key.
     *
     * @return string
     */
    public function getSessionKey(): string
    {
        return $this->getResourceSlug() . '-mega-filter-columns';
    }

    private function getFilterState(NovaRequest $request, MegaFilter $card): Collection
    {
        $value = $this->getFilterColumns();

        if (!$value) {
            $value = session($this->getSessionKey());
        }

        $attributes = $card->columns()->filter(static function (Column $column) use ($value) {

            if ($column->permanent) {
                return true;
            }

            if (is_array($value) && is_bool($value = $value[$column->attribute])) {
                return $value;
            }
            return $column->checked;
        });

        return $attributes->pluck('attribute')->values();
    }

    /**
     * Get the filters for the given request.
     *
     * @param NovaRequest $request
     *
     * @return Collection
     */
    public function resolveFilters(NovaRequest $request): Collection
    {
        if ($this->shouldApplyMegaFilter($request) && $card = $this->getMegaFilterCard($request)) {
            $filterColumns = $this->getFilterColumns();

            if ($filterColumns) {
                session([$this->getSessionKey() => $filterColumns]);
            }
            return parent::resolveFilters($request)->merge($card->filters());
        }

        return parent::resolveFilters($request);
    }
}
`

**Comment by khitas** [comment]
> Fast solution to #52 #51. Corrections welcome

I follow your steps from d47e2c9 but the bug remains. Can you please help?

**Comment by Andriichello** [comment]
> > Fast solution to #52 #51. Corrections welcome
> 
> I follow your steps from [d47e2c9](https://github.com/dcasia/nova-mega-filter/commit/d47e2c9f35900df3f60294b8ed12e1cf50d1fe8a) but the bug remains. Can you please help?

I don't really remember that approach, because later on I had rewritten all of it (I only needed to select columns to be visible on index). I've changed the Vue components as well as the PHP code, so there is no simple solution. Here is the repo: https://github.com/Andriichello/nova-columns-card

**Pull request merged**
