### PR TITLE
Fix duplicate API calls

### PR DESCRIPTION
**Pull request by bocanhcam**
When changing the filter input value the API will be called duplicate multiple times.

[Screencast from 29-05-2024 17:47:06.webm](https://github.com/dcasia/nova-mega-filter/assets/35592955/d87f09d0-fa0b-4364-a0f2-338415a9e01a)

### CODE REVIEW

**Comment by milewski** [comment]
Im sure that these events were needed to update the table bellow once the filter changed... are you sure things are still working correctly after commenting it out?

**Comment by bocanhcam** [comment]
Yes. I have tested and It is working perfectly fine.

**Comment by bocanhcam** [comment]
hey @milewski . Is there any problem? I think the table already handle reload when query filter change.

**Comment by milewski** [comment]
I had forgotten about this PR .. thanks I merged it now

**Pull request merged**
